import Form from "components/Form";
import SideBar from "components/SideBar";
import Layout from "layout";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
	const [step, setStep] = useState(1);

	const handleStep = (step: number) => setStep(step);
	return (
		<Layout>
			<Head>
				<title>Multi Step Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SideBar currentStep={step} handleStep={handleStep} />
			<Form currentStep={step} handleStep={handleStep} />
		</Layout>
	);
}
