import Form from "components/Form";
import SideBar from "components/SideBar";
import ValuesProvider from "context/valuesContext";
import Layout from "layout";
import Head from "next/head";

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Multi Step Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ValuesProvider>
				<SideBar />
				<Form />
			</ValuesProvider>
		</Layout>
	);
}
